In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [27]:
dataset = pd.read_csv('bola.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [28]:
print(x)

[['Inggris' 25.0 178.0]
 ['Argentina' 32.0 173.0]
 ['Inggris' 28.0 175.0]
 ['Jerman' 25.0 180.0]
 ['Spanyol' 29.0 nan]
 ['Inggris' 20.0 nan]
 ['Portugal' 26.0 180.0]
 ['Brazil' 35.0 185.0]
 ['Jerman' 31.0 185.0]
 ['Jerman' 31.0 180.0]
 ['Jerman' 34.0 193.0]
 ['Portugal' 36.0 187.0]
 ['Spanyol' 27.0 nan]
 ['Spanyol' 34.0 182.0]
 ['Argentina' 33.0 173.0]
 ['Brazil' 29.0 177.0]
 ['Prancis' 22.0 172.0]
 ['Prancis' nan nan]
 ['Prancis' nan nan]]


In [29]:
print(y)

['Belum' 'Belum' 'Belum' 'Belum' 'Sudah' 'Belum' 'Belum' 'Belum' 'Sudah'
 'Belum' 'Sudah' 'Sudah' 'Sudah' 'Sudah' 'Sudah' 'Sudah' 'Belum' 'Sudah'
 'Belum']


In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] = imputer.transform(x[:,1:3])

In [31]:
print(x)

[['Inggris' 25.0 178.0]
 ['Argentina' 32.0 173.0]
 ['Inggris' 28.0 175.0]
 ['Jerman' 25.0 180.0]
 ['Spanyol' 29.0 180.0]
 ['Inggris' 20.0 180.0]
 ['Portugal' 26.0 180.0]
 ['Brazil' 35.0 185.0]
 ['Jerman' 31.0 185.0]
 ['Jerman' 31.0 180.0]
 ['Jerman' 34.0 193.0]
 ['Portugal' 36.0 187.0]
 ['Spanyol' 27.0 180.0]
 ['Spanyol' 34.0 182.0]
 ['Argentina' 33.0 173.0]
 ['Brazil' 29.0 177.0]
 ['Prancis' 22.0 172.0]
 ['Prancis' 29.235294117647058 180.0]
 ['Prancis' 29.235294117647058 180.0]]


In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder ='passthrough')
x = np.array(ct.fit_transform(x))

In [33]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 25.0 178.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 32.0 173.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 28.0 175.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 25.0 180.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 29.0 180.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 20.0 180.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 26.0 180.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 35.0 185.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 31.0 185.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 31.0 180.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 34.0 193.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 36.0 187.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.0 180.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 34.0 182.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 33.0 173.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 29.0 177.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 22.0 172.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 29.235294117647058 180.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 29.235294117647058 180.0]]


In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [36]:
print(y)

[0 0 0 0 1 0 0 0 1 0 1 1 1 1 1 1 0 1 0]


In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [37]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 28.0 175.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 33.0 173.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 29.0 180.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 22.0 172.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 35.0 185.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 32.0 173.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 34.0 182.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 25.0 178.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 29.235294117647058 180.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 29.235294117647058 180.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 31.0 180.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 31.0 185.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.0 180.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 36.0 187.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 20.0 180.0]]


In [38]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 25.0 180.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 29.0 177.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 26.0 180.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 34.0 193.0]]


In [39]:
print(y_train)

[0 1 1 0 0 0 1 0 0 1 0 1 1 1 0]


In [40]:
print(y_test)

[0 1 0 1]


In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [42]:
print(x_train)

[[0.0 0.0 1.0 -0.3922322702763681 -0.2672612419124244
  -0.49999999999999994 -0.49999999999999994 -0.3247981457305463
  -0.9900901081587404]
 [1.0 0.0 0.0 -0.3922322702763681 -0.2672612419124244
  -0.49999999999999994 -0.49999999999999994 0.8097707194925932
  -1.4470547734627734]
 [0.0 0.0 0.0 -0.3922322702763681 -0.2672612419124244
  -0.49999999999999994 1.9999999999999998 -0.09788437268591837
  0.15232155510134218]
 [0.0 0.0 0.0 -0.3922322702763681 -0.2672612419124244 1.9999999999999998
  -0.49999999999999994 -1.6862807839983136 -1.6755371061147901]
 [0.0 1.0 0.0 -0.3922322702763681 -0.2672612419124244
  -0.49999999999999994 -0.49999999999999994 1.263598265581849
  1.2947332183614249]
 [1.0 0.0 0.0 -0.3922322702763681 -0.2672612419124244
  -0.49999999999999994 -0.49999999999999994 0.5828569464479653
  -1.4470547734627734]
 [0.0 0.0 0.0 -0.3922322702763681 -0.2672612419124244
  -0.49999999999999994 1.9999999999999998 1.036684492537221
  0.6092862204053753]
 [0.0 0.0 1.0 -0.39223227027

In [43]:
print(x_test)

[[0.0 0.0 0.0 2.5495097567963927 -0.2672612419124244 -0.49999999999999994
  -0.49999999999999994 -1.0055394648644298 0.15232155510134218]
 [0.0 1.0 0.0 -0.3922322702763681 -0.2672612419124244
  -0.49999999999999994 -0.49999999999999994 -0.09788437268591837
  -0.5331254428547074]
 [0.0 0.0 0.0 -0.3922322702763681 3.7416573867739413 -0.49999999999999994
  -0.49999999999999994 -0.778625691819802 0.15232155510134218]
 [0.0 0.0 0.0 2.5495097567963927 -0.2672612419124244 -0.49999999999999994
  -0.49999999999999994 1.036684492537221 3.122591879577557]]
